import { Inter } from "next/font/google";
import "./globals.css";
import GlobaProvider from "./context/GlobaProvider";
import Nav from "./components/nav";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <GlobaProvider>
          <Nav/>
          {children}
          <Footer/>
        </GlobaProvider>
        
        </body>
    </html>
  );
}
